### ISSUE TITLE
about the required dataset and practicing steps

### ISSUE THREAD

**Issue by amiltonwong** [tolgabirdal/qecnetworks#1]
Hi, @tolgabirdal , @yongheng1991 ,

Thanks for releasing the packages. It seems that the dataset is not released yet. Could you help to release it? If the dataset is not ready, could you list the steps on how to modify the existing dataset(e.g, ShapeNet) for trying the QEC-Net ?

THX!

**Comment by dilaragokay** [comment]
Hi @amiltonwong,

The instructions to prepare the dataset are available now — you can find them at [dataset_preparation.ipynb](https://github.com/tolgabirdal/qecnetworks/blob/master/dataset_preparation.ipynb).

**Comment by amiltonwong** [comment]
@dilaragokay , thanks a lot! I'll try it. :)

**Comment by tolgabirdal** [comment]
@amiltonwong I'm guessing things have worked out and closing this issue. Let us know otherwise.
