### ISSUE TITLE
Application of the qec network

### ISSUE THREAD

**Issue by honggudrnjs** [tolgabirdal/qecnetworks#2]
Thanks for sharing the code of your amazing work!
By the way, I am curious about the experimental validation of the work.
Since it is quaternion-**equivariant**, I would rather apply this method to rotated localization or segmentation.
However, classification seems to be a major target of the work, right?

**Comment by tolgabirdal** [comment]
Thanks for the kind words @honggudrnjs. Well, we do focus on 3D settings (so localization from a point cloud might be an option). Though, we have 3D object pose estimation experiments besides classification. I agree that many equivariant networks focused on invariant-classification. This is what we wanted to avoid and hence included the experiments on relative rotation estimation.

**Comment by honggudrnjs** [comment]
Thanks for your quick reply :) I thought rotation-invariant module would fit to rotated classification task more than rotation-equivariant module conceptually.

**Comment by tolgabirdal** [comment]
I fully agree. Our network has both invariant (activations) and equivariant (pose capsules) part. We evaluate the invariance on classification (so does many other rotation equivariant networks) and equivariance on relative pose estimation.

**Comment by honggudrnjs** [comment]
Thanks for the quick reply again :) Thanks to your recent works, I became interested in capsule networks and appreciate it. I hope more amazing capsule network properties can be discovered.

**Comment by tolgabirdal** [comment]
Great to hear. Looking forward to more works in this area. May I close this issue now?

**Comment by honggudrnjs** [comment]
Closed it :)
