### ISSUE TITLE
How to compute LRF?

### ISSUE THREAD

**Issue by yokinglou** [tolgabirdal/qecnetworks#8]
Hi,

can you provide detailed instructions for computing LRFs by FLARE in PCL?

Thanks.

**Comment by dilaragokay** [comment]
Hi @yokinglou,

You can fetch https://github.com/tolgabirdal/qecnetworks/pull/7 for computing LRFs.

**Comment by tolgabirdal** [comment]
merged :)

**Comment by yokinglou** [comment]
I see. Thanks :)
