### ISSUE TITLE
Q: How do you generate the rotation (*_rot.txt) files?

### ISSUE THREAD

**Issue by elias-Mimetrik** [tolgabirdal/qecnetworks#9]
The code does not say how the rotation txt files e.g. `plant/plant_0163_rot.txt` are generated.

How is this done please? Thank you.

**Comment by dilaragokay** [comment]
The rotation files are generated at [flare_estimation.cpp](https://github.com/tolgabirdal/qecnetworks/blob/master/flare/flare_estimation.cpp) but with `*_lrf.txt` suffix. So, changing `_rot.txt` to `_lrf.txt` in [dataset_preparation.ipynb](https://github.com/tolgabirdal/qecnetworks/blob/master/dataset_preparation.ipynb) should solve the issue. You can also find the change in https://github.com/tolgabirdal/qecnetworks/pull/10.

**Comment by elias-Mimetrik** [comment]
The following segment will also need to be updated (first 3 values must be ignored):
```
vecs[0] = [float(lrf[3]), float(lrf[4]), float(lrf[5])] # x
vecs[1] = [float(lrf[6]), float(lrf[7]), float(lrf[8])] # y
vecs[2] = [float(lrf[9]), float(lrf[10]), float(lrf[11][:-1])] # z - don't take last char since it is \n
```

**Comment by dilaragokay** [comment]
Thank you for sharing this, it looks correct. I included this change in https://github.com/tolgabirdal/qecnetworks/pull/10.
